# Clock signal
set_property PACKAGE_PIN W5 [get_ports clk_100MHz]							
	set_property IOSTANDARD LVCMOS33 [get_ports clk_100MHz]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk_100MHz]
## Switches
 set_property PACKAGE_PIN V17 [get_ports {a[0]}]					
	 set_property IOSTANDARD LVCMOS33 [get_ports {a[0]}]
 set_property PACKAGE_PIN V16 [get_ports {a[1]}]					
	 set_property IOSTANDARD LVCMOS33 [get_ports {a[1]}]
 set_property PACKAGE_PIN W16 [get_ports {a[2]}]					
	 set_property IOSTANDARD LVCMOS33 [get_ports {a[2]}]
 set_property PACKAGE_PIN W17 [get_ports {a[3]}]					
	 set_property IOSTANDARD LVCMOS33 [get_ports {a[3]}]
 set_property PACKAGE_PIN W15 [get_ports {a[4]}]					
	 set_property IOSTANDARD LVCMOS33 [get_ports {a[4]}]
 set_property PACKAGE_PIN V15 [get_ports {a[5]}]					
	 set_property IOSTANDARD LVCMOS33 [get_ports {a[5]}]
 set_property PACKAGE_PIN W14 [get_ports {a[6]}]					
	 set_property IOSTANDARD LVCMOS33 [get_ports {a[6]}]
 set_property PACKAGE_PIN W13 [get_ports {a[7]}]					
	 set_property IOSTANDARD LVCMOS33 [get_ports {a[7]}]
 set_property PACKAGE_PIN V2 [get_ports {a[8]}]					
	 set_property IOSTANDARD LVCMOS33 [get_ports {a[8]}]
# LEDs
set_property PACKAGE_PIN U16 	 [get_ports {LED[0]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {LED[0]}]
set_property PACKAGE_PIN E19 	 [get_ports {LED[1]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
set_property PACKAGE_PIN U19 	 [get_ports {LED[2]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}]
set_property PACKAGE_PIN V19 	 [get_ports {LED[3]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {LED[3]}]
set_property PACKAGE_PIN W18 	 [get_ports {LED[4]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {LED[4]}]
set_property PACKAGE_PIN U15 	 [get_ports {LED[5]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {LED[5]}]
set_property PACKAGE_PIN U14 	 [get_ports {LED[6]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {LED[6]}]
set_property PACKAGE_PIN V14 	 [get_ports {LED[7]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {LED[7]}]

#7 segment display
set_property PACKAGE_PIN W7 	 [get_ports {seg[0]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]
set_property PACKAGE_PIN W6 	 [get_ports {seg[1]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
set_property PACKAGE_PIN U8 	 [get_ports {seg[2]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
set_property PACKAGE_PIN V8 	 [get_ports {seg[3]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
set_property PACKAGE_PIN U5 	 [get_ports {seg[4]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
set_property PACKAGE_PIN V5 	 [get_ports {seg[5]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
set_property PACKAGE_PIN U7 	 [get_ports {seg[6]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]

set_property PACKAGE_PIN U2 	 [get_ports {an[0]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {an[0]}]
set_property PACKAGE_PIN U4 	 [get_ports {an[1]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {an[1]}]
set_property PACKAGE_PIN V4 	 [get_ports {an[2]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {an[2]}]
set_property PACKAGE_PIN W4 	 [get_ports {an[3]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {an[3]}]

##Buttons
## btnL
set_property PACKAGE_PIN W19 	 [get_ports btn1]						
set_property IOSTANDARD LVCMOS33 [get_ports btn1]
## btnR
set_property PACKAGE_PIN T17 	 [get_ports btn2]						
set_property IOSTANDARD LVCMOS33 [get_ports btn2]
set_property PACKAGE_PIN U18     [get_ports reset]						
set_property IOSTANDARD LVCMOS33 [get_ports reset]

##USB-RS232 Interface
set_property PACKAGE_PIN B18 [get_ports rx]						
set_property IOSTANDARD LVCMOS33 [get_ports rx]
set_property PACKAGE_PIN A18 [get_ports tx]						
set_property IOSTANDARD LVCMOS33 [get_ports tx]
